"""This module contains the database schema for the TPS system in Markdown format."""
schema = ("""
## DATABASE SCHEMA

### component
| Column | Type |
| --- | --- |
| id | integer |
| name | text |
| version | text |
| release | text |
| description | text |
| supplier | text |
| root_supplier | text |
| editors_grouper | text |
| origin_tag | text |
| subpart | boolean |
| cloned_from_component_fk | integer |
| intelli_shield_known_name | text |
| klm_component | boolean |
| klm_exception_fk | integer |
| license_guess | text |
| deleted | boolean |
| created_at | timestamptz |
| updated_at | timestamptz |
| lca_results | text |
| inc_run_date | timestamptz |
| license_declared | text |
| lca_plugin | text |
| code_type | text |
| distro_name | text |
| distro_version | text |

### image
| Column | Type |
| --- | --- |
| id | integer |
| md5sum | text |
| created_at | timestamptz |
| updated_at | timestamptz |
| name | text |
| deleted | boolean |
| sha1 | text |
| sha256 | text |
| sha512 | text |
| open_source_state | text |
| commercial_state | text |
| corona_image_id | text |
| bom_status | text |
| bom_registration_status | text |
| bom_incomplete | boolean |
| bom_incomplete_reason | text |
| bom_registration_message | text |
| cisco_part_number | text |
| version_less_components_count | integer |
| eng_contact | text |
| security_contact | text |
| additional_metadata | text |
| image_source | text |
| csdl_id | text |
| part80 | text |
| gold_candidate_status | text |
| gc_received_date | timestamptz |
| gc_completed_date | timestamptz |
| gc_corona_release_id | text |
| spdx_status | text |
| spdx_location | text |
| spdx_generated_on | timestamptz |
| spdx_failure_reason | text |
| cvr_image_name | text |
| spdx_json | jsonb |
| spdx_ingestion_status | text |
| spdx_ingestion_failure_reason | text |
| cvr_image_name_metadata | text |
| spdx_contains_commercial_components | boolean |
| has_conflicting_component_types | boolean |
| conflicting_component_type_list | text |
| has_kernel_components | boolean |
| build_script_status | text |
| has_modified_components | boolean |
| modified_components_status | text |

### image_permits
| Column | Type |
| --- | --- |
| id | integer |
| image_fk | integer |
| permit_fk | integer |
| modified | boolean |
| source_data | text |
| source_code_file_path | text |
| file_hash | text |
| file_size | integer |
| upload_status | text |
| uploaded_by | text |
| uploaded_date | timestamptz |

### license
| Column | Type |
| --- | --- |
| id | integer |
| name | text |
| version | text |
| text | text |
| deleted | boolean |
| owner | text |
| state | text |
| patent_clause | text |
| attorney_notes | text |
| publication_required | boolean |
| documentation_required | boolean |
| patent_clause_required | boolean |
| type | text |
| reputable | boolean |
| copyleft_strength | text |
| provisional | boolean |
| default_priority | text |
| inc_run_date | timestamptz |
| requires_full_compliance | boolean |
| spdx_id | text |
| is_restricted_kernel_license | boolean |

### license_urls
| Column | Type |
| --- | --- |
| id | integer |
| description | text |
| url | text |
| license_fk | integer |
| inc_run_date | timestamptz |

### notification
| Column | Type |
| --- | --- |
| id | integer |
| template_id | text |
| subject | text |
| message | text |
| sent_at | timestamptz |
| priority | text |

### notification_to_users
| Column | Type |
| --- | --- |
| id | integer |
| userid | text |
| notification_fk | integer |
| read | boolean |

### permit
| Column | Type |
| --- | --- |
| id | integer |
| license_fk | integer |
| component_fk | integer |
| scope | text |
| status | text |
| preparer | text |
| legal_approver | text |
| requested_date | timestamptz |
| submitted_date | timestamptz |
| approved_date | timestamptz |
| message | text |
| waiting_on | text |
| open_source_permit | boolean |
| commercial_permit | boolean |
| cisco_proprietary_permit | boolean |
| is_custom_permit | text |
| copyleft | integer |
| priority | text |
| commercial_sub_asset_status | text |
| manual_review_reason | text |
| manual_review_requested_by | text |
| deleted | boolean |
| comment_fk | integer |
| last_state_change_date | timestamptz |
| cms_contract_number | text |
| support_start_date | timestamptz |
| support_end_date | timestamptz |
| effective_start_date | timestamptz |
| effective_end_date | timestamptz |
| renewal_type | text |
| days_for_notification | integer |
| support_years_after_term | integer |
| vap_id | text |
| royalty_bearing | text |
| editors_grouper | text |
| k_l_m_exception_request_fk | integer |
| cisco_part_number | text |
| created_date | timestamptz |
| eclm_ids | text |
| cdp_link | text |
| inc_run_date | timestamptz |
| manual_review_requested | boolean |
| requires_maintenance_and_support | boolean |
| maintenance_and_support_cpn | text |

### permit_comment
| Column | Type |
| --- | --- |
| id | integer |
| commenter | text |
| subject | text |
| body | text |
| created_date | timestamptz |
| deleted | boolean |
| inc_run_date | timestamptz |

### product
| Column | Type |
| --- | --- |
| id | integer |
| name | text |
| created_at | timestamptz |
| updated_at | timestamptz |
| deleted | boolean |
| corona_product_id | text |
| cvr_product_name | text |
| cvr_product_name_metadata | text |
| esp_id | text |

### product_history
| Column | Type |
| --- | --- |
| id | integer |
| product_id | integer |
| timestamp | timestamptz |
| field_name | text |
| user_id | text |
| type | text |
| new_value | text |
| old_value | text |

### release
| Column | Type |
| --- | --- |
| id | integer |
| product_fk | integer |
| version | text |
| description | text |
| created_at | timestamptz |
| updated_at | timestamptz |
| fcs_date | timestamptz |
| open_source_state | text |
| commercial_state | text |
| state | text |
| deleted | boolean |
| documentation_file_path | text |
| documentationwemfile_path | text |
| corona_release_id | text |
| os_assets_affirmed | boolean |
| os_responsible_parties_set | boolean |
| p1_p2_constraints_verified | boolean |
| documentation_added | boolean |
| publication_added | boolean |
| comm_assets_affirmed | boolean |
| comm_responsible_parties_set | boolean |
| royalty_bearings_set | boolean |
| is_cloud_validated_by | text |
| locked | boolean |
| release_type | text |
| csdl_id | text |
| predecessor_release_fk | integer |
| predecessor_assigned_by | text |
| component_usage_changed | boolean |
| is_bundle | boolean |
| rms_completed | boolean |
| no_o_s_permits_asserted | boolean |
| no_o_s_permits_asserted_note | text |
| no_o_s_permits_asserter | text |
| no_commercial_permits_asserted | boolean |
| no_commercial_permits_asserter | text |
| csdl_id_rolled_up | boolean |
| corona_csdl_id | text |
| documentation_failure_reason | text |
| documentation_status | text |
| doc_cisco_product_name | text |
| doc_cisco_product_release | text |
| os_specialist_assigned | text |
| comm_specialist_assigned | text |
| has_deviations | boolean |
| download_status | text |
| download_location | text |
| downloaded_on | timestamptz |
| download_commercial_only | boolean |
| download_failure_reason | text |
| spdx_status | text |
| spdx_location | text |
| spdx_generated_on | timestamptz |
| spdx_failure_reason | text |
| cloud_market_place | text |
| cvr_release_name | text |
| cvr_release_name_metadata | text |
| spdx_contains_commercial_components | boolean |
| doc_pub_regeneration | boolean |
| doc_pub_regeneration_status | text |
| regeneration_date | timestamptz |
| build_script | text |
| is_imageless | boolean |
| build_script_status | text |
| has_kernel_components | boolean |
| is_kernel_acknowledged | boolean |
| kernel_acknowledged_user | text |
| deletion_reason | text |
| eos_eol_link | text |
| deletion_user_id | text |
| eos_eol_date | timestamptz |
| release_deletion_status | text |
| deletion_rejection_reason | text |
| green_date | timestamptz |
| has_new_kernel_components | boolean |
| release_score | integer |
| third_party_notice_status | text |
| third_party_notice_file_path | text |
| third_party_notice_failure_reason | text |
| build_script_modularization_status | text |
| modular_build_script_status | text |
| pub_regeneration | boolean |
| pub_regeneration_status | text |
| pub_regeneration_date | timestamptz |
| doc_regeneration | boolean |
| doc_regeneration_status | text |
| doc_regeneration_date | timestamptz |
| has_modified_components | boolean |
| modified_components_status | text |

### release_images
| Column | Type |
| --- | --- |
| release_fk | integer |
| image_fk | integer |
| completed_image_hash | text |

""")
